version: "3.9"

services:
  web:
    image: nginx
    volumes:
      - ./build:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=website.com
      - NGINX_PORT=80